# FossID-DA Configuration for Dart/Flutter
# Applies to: Pub, Flutter projects

[dependency-analysis]
# Add supported package managers for this ecosystem
supported_package_managers = ["Pub"]

[dependency-analysis.scan_options]
# Lock file handling
# If 0, uses lock files (pubspec.lock) when available
# If 1, ignores lock files and uses pubspec.yaml
da_ignore_lock_manifests = 0

[dependency-analysis.dependency_scopes]
da_ds_dependency_overrides = 0    # Override specific dependencies

[dependency-analysis.graph_depth]
# Set maximum depth for dependency tree traversal
da_gd_general = 4

[dependency-analysis.ignore_settings]
da_ignore_folders = "" 