# FossID-DA Configuration for Swift/Objective-C
# Applies to: CocoaPods, Carthage, Swift Package Manager

[dependency-analysis]
# Add supported package managers for this ecosystem
supported_package_managers = ["CocoaPods"]

[dependency-analysis.system_settings]
# Operating system setting (important for Swift/Objective-C dependencies)
# Supported values: win32, win64, darwin, debian, unix
da_os_type = "darwin"      # macOS/iOS development typically uses darwin

# Version settings
da_cocoapod_version = "1.15.2"
da_swift_version = "5.10"

[dependency-analysis.git_options]
# GitHub token for API requests (highly recommended)
da_git_user = ""
da_git_token = ""          # Without a token, rate limits apply (60 queries/hour)

[dependency-analysis.scan_options]
# Lock file handling
# If 0, uses lock files (Podfile.lock, Cartfile.resolved) when available
# If 1, ignores lock files and uses Podfile, Cartfile
da_ignore_lock_manifests = 0

[dependency-analysis.graph_depth]
# Set maximum depth for dependency tree traversal
da_gd_cocoapod = 4

[dependency-analysis.ignore_settings]
da_ignore_folders = "" 