# FossID-DA Configuration for Elixir
# Applies to: Mix, Hex package manager

[dependency-analysis.system_settings]
# Operating system setting
# Supported values: win32, win64, darwin, debian, unix
da_os_type = "linux"      # Affects NIFs (Native Implemented Functions) and OS-specific packages

[dependency-analysis.scan_options]
# Lock file handling
# If 0, uses lock files (mix.lock) when available
# If 1, ignores lock files and uses mix.exs
da_ignore_lock_manifests = 0

# Use single dependency version in dependency tree
da_single_dependency_versions = 0

# Ignore hidden files from being processed
da_ignore_hidden_files = 1

[dependency-analysis.dependency_scopes]
da_ds_test_dependencies = 0    # Dependencies with only: :test in deps() function
da_ds_dev_dependencies = 0     # Dependencies with only: :dev in deps() function
da_ds_optional_dependencies = 0 # Dependencies with optional: true in deps() function

[dependency-analysis.graph_depth]
# Set maximum depth for dependency tree traversal
da_gd_general = 4

[dependency-analysis.ignore_settings]
da_ignore_folders = "" 