# FossID-DA Configuration for Rust/Cargo
# Applies to: Cargo projects

[dependency-analysis]
# Add supported package managers for this ecosystem
supported_package_managers = ["Cargo"]

[dependency-analysis.system_settings]
# Operating system setting (corresponds to Rust's target-specific dependencies)
# Supported values: win32, win64, darwin, debian, unix
da_os_type = "linux"      # Affects conditional dependencies with [target.'cfg(unix)'.dependencies]

[dependency-analysis.scan_options]
# Lock file handling
# If 0, uses lock files (Cargo.lock) when available
# If 1, ignores lock files and uses Cargo.toml
da_ignore_lock_manifests = 0

[dependency-analysis.dependency_scopes]
da_ds_test_dependencies = 0        # Dependencies in [dev-dependencies] used in #[cfg(test)]
da_ds_dev_dependencies = 0         # Development tools in [dev-dependencies] like clippy, rustfmt
da_ds_optional_dependencies = 0    # Features declared with [features] and optional = true

[dependency-analysis.graph_depth]
# Set maximum depth for dependency tree traversal
da_gd_cargo = 4

[dependency-analysis.ignore_settings]
da_ignore_folders = "" 